version: "1"
services:
  notespese-frontend:
    stdin_open: true
    tty: true
    container_name: notespese-frontend 
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env